# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: "2019-05-23T01:49:05Z"
  generation: 2
  labels:
    app: kubia
  name: kubia
  namespace: default
  resourceVersion: "34315"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/kubia
  uid: f274a78e-7cfc-11e9-96eb-0800276e487f
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubia
    spec:
      containers:
      - image: dpereira99/kubia:stable
        imagePullPolicy: IfNotPresent
        name: kubia
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - 127.0.0.1:8080
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 3
  observedGeneration: 2
  readyReplicas: 1
  replicas: 3
